### ISSUE TITLE
Unable to install on Laravel 10

### ISSUE THREAD

**Issue by vesper8** [beyondcode/tinkerwell-helper#21]

**Comment by paulinofonsecas** [comment]
2

**Comment by msiemaszko** [comment]
same.

**Comment by MasterOfWeb** [comment]
same

**Comment by nam-co** [comment]
Has this been fixed? It would be great if it also allowed a measure function, where it outputs time to complete like ray()

**Comment by gmgarrison** [comment]
I followed the instructions [here](https://aschmelyun.com/blog/installing-a-local-composer-package-in-your-php-project/) to install a local copy but couldn't get it to open Tinkerwell when called from an artisan command.

**Comment by nam-co** [comment]
maybe for Version 11 please @mpociot

**Comment by dubbows** [comment]
Problem to install on laravel 10

**Comment by nam-co** [comment]
Has any body tried the shift version? https://github.com/beyondcode/tinkerwell-helper/pull/20

**Comment by sschlein** [comment]
10+11 done :)
