### ISSUE TITLE
Launches over and over

### ISSUE THREAD

**Issue by jhoff** [beyondcode/tinkerwell-helper#4]
Just trying this out for the first time and when I put `tinker()` in my app and refreshed the page, Tinkerwell will launch but if I click on anything in the background or try and close the app it immediately re-launches / comes to the front. I literally have to race it back in the editor to comment the line and save the file.

OS X Catalina 10.15.3
Crome 80.0.3987.87
Tinkerwell 2.2.1
Tinkerwell-helper 1.0.0

**Comment by sschlein** [comment]
It sounds like you've added it somewhere that is used while bootstrapping the app and so this causes the issues. If this is a different issue, please let me know and I'll look into it.
