### ISSUE TITLE
Packagist is not auto-updated

### ISSUE THREAD

**Issue by stefro** [beyondcode/tinkerwell-helper#9]
Thanks @mpociot  for merging the Laravel 7 compatibility pull request!

However, Packagist is not configured to be auto updated (https://packagist.org/packages/beyondcode/tinkerwell-helper).

So composer is still trying to install the old 1.0 version instead of the 1.1. The dev-master branch according to packagist is also still the old one. Can you please update packagist?

Thanks!

**Comment by sschlein** [comment]
Cleaning up (has been solved a while ago)
